# Generated by Django 3.2.6 on 2021-12-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0002_test_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='plural',
            field=models.CharField(default='fios', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testevent',
            name='state',
            field=models.CharField(choices=[('Running', 'Running'), ('Created Locally', 'Created Locally'), ('Custom Resource Created', 'Crd Created'), ('Pod Created', 'Pod Created'), ('Started Container', 'Started Container'), ('Failed', 'Failed'), ('Completed', 'Completed'), ('Uknown', 'Unknown'), ('Job Completed', 'Job Completed'), ('Deleted Resource', 'Resource Deleted')], default='Uknown', max_length=30),
        ),
    ]
