# Generated by Django 3.2.6 on 2021-12-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0003_auto_20211215_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='iperftestresult',
            name='client_ip',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iperftestresult',
            name='duration',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iperftestresult',
            name='protocol',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iperftestresult',
            name='received_MB_s',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iperftestresult',
            name='sent_MB_s',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iperftestresult',
            name='server_ip',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='test_status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('CREATED LOCALLY', 'Created Locally'), ('CREATED', 'Created'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STARTED', 'Started'), ('UNKOWN', 'Unknown')], default='UNKOWN', max_length=30),
        ),
    ]
