# Generated by Django 3.2.6 on 2022-01-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0005_iperftestresult_system_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(choices=[('FIO', 'Fio'), ('PGBENCH', 'Pgbench'), ('Iperf3', 'Iperf3'), ('UNKOWN', 'Unknown')], default='UNKNOWN', max_length=15),
        ),
    ]
