# Generated by Django 3.2.6 on 2022-01-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0006_auto_20220104_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='role',
            new_name='architecture',
        ),
        migrations.AddField(
            model_name='node',
            name='os',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
