# Generated by Django 3.2.6 on 2022-01-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0009_auto_20220107_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgbenchtestconfig',
            name='duration_in_seconds',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='pgbenchtestconfig',
            name='number_of_clients',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='pgbenchtestconfig',
            name='selects_only',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
