# Generated by Django 3.2.6 on 2022-01-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0010_auto_20220107_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgbenchtestconfig',
            name='port',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pgbenchtestconfig',
            name='db_pw',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pgbenchtestconfig',
            name='duration_in_seconds',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pgbenchtestconfig',
            name='number_of_clients',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='pgbenchtestconfig',
            name='selects_only',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
