# Generated by Django 3.2.6 on 2022-01-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0011_auto_20220107_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgbenchtestconfig',
            name='scaling_factor',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='pgbenchtestconfig',
            name='thread_count',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
