# Generated by Django 3.2.6 on 2022-01-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0012_auto_20220110_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgbenchtestconfig',
            name='node_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
