# Generated by Django 3.2.6 on 2022-01-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0013_pgbenchtestconfig_node_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgbenchtestresult',
            old_name='latency_average',
            new_name='latency_average_in_ms',
        ),
        migrations.AddField(
            model_name='pgbenchtestresult',
            name='duration_in_seconds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pgbenchtestresult',
            name='scaling_factor',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
