# Generated by Django 3.2.6 on 2022-01-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0014_auto_20220112_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgbenchtestresult',
            name='latency_average_in_ms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pgbenchtestresult',
            name='number_of_transactions_processed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
