# Generated by Django 3.2.6 on 2022-01-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0015_auto_20220112_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgbenchtestresult',
            old_name='total_transactions',
            new_name='initial_connection_time_in_ms',
        ),
    ]
