# Generated by Django 3.2.6 on 2022-01-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0016_rename_total_transactions_pgbenchtestresult_initial_connection_time_in_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='iperftestresult',
            name='transmission_rate_per_second',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iperftestresult',
            name='system_info',
            field=models.CharField(max_length=80),
        ),
    ]
