# Generated by Django 3.2.6 on 2022-02-09 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0017_auto_20220124_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgbenchtestresult',
            name='id',
        ),
        migrations.AddField(
            model_name='pgbenchtestresult',
            name='test',
            field=models.OneToOneField(blank=True, default=128, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pgbenchTestResult', serialize=False, to='test_service.test'),
            preserve_default=False,
        ),
    ]
