# Generated by Django 3.2.6 on 2022-02-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0018_auto_20220209_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiotestconfig',
            name='pv_claim_name',
            field=models.CharField(default='mypvclaim', max_length=150),
            preserve_default=False,
        ),
    ]
